#!/bin/zsh

#check if there is no argument
if [[ -z "$1" ]]; then
    echo "no arguments provided"
    exit 1
fi

#check if there is no argument
if [[ -z "$2" ]]; then
    echo "no arguments provided"
    exit 1
fi

aws s3api delete-object --bucket $1 --key $2 --region us-east-1